name: Deploy/Update contracts
# On push to deployments branch, run the workflow
on:
  push:
    branches:
      - deploy-V1
# Environment variables
env:
  MNEMONIC: ${{ secrets.MNEMONIC_TEST }}
  MUMBAI_URL: ${{ secrets.MUMBAI_URL }}

jobs:
  deploy:
    # OS to run on
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout the repo
        uses: actions/checkout@v3
          ref: main
      # Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      # move to smart-contract folder and install dependencies (ci clean install)
      - name: Install dependencies
        run: cd smart-contract && npm ci
      # Run V1 deploy script
      - name: deploy-contracts
        run: npx hardhat deploy --deploy-scripts ./deploy/V1
      # push changes to main branch
      - name: Commit changes
        run: |
          git config --global user.email "nazhirgonzalez@gmail.com"
          git config --global user.name "nazhG"
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy V1" && git push origin HEAD:main
