name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "World"

env:
  MNEMONIC: ${{ secrets.MNEMONIC_TEST }}
  MUMBAI_URL: ${{ secrets.MUMBAI_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: echo "Hello ${{ github.event.inputs.name }}!"