name: Deploy/Update contracts to V2

on:
  push:
    branches:
      - deploy-V2
      
env:
  MNEMONIC: ${{ secrets.MNEMONIC_TEST }}
  MUMBAI_URL: ${{ secrets.MUMBAI_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: cd smart-contracts && pnpm install

      - name: deploy-contracts
        run: npx hardhat deploy --deploy-scripts ./deploy/V2 --network mumbai

      - name: Commit changes
        run: |
          git config --global user.email "nazhirgonzalez@gmail.com"
          git config --global user.name "nazhG"
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy V2" && git push origin HEAD:main
